services:
  app:
    # Build the image using the Dockerfile in the current directory
    build: .
    container_name: pinteV1.2front

    # Expose the port 80 from the container to port 80 on your machine #
    ports:
      - "443:443"

    volumes:
    - /home/ubuntu/certbot/conf:/etc/letsencrypt
    - /home/ubuntu/certbot/www:/var/www/certbot

    # Ensure the container runs as a background process (daemon)
    restart: unless-stopped

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email andrebastos85@gmail.com -d controlepinte.com.br -d www.controlepinte.com.br --agree-tos

